---
title: "Bookings Recorded by Coos"
output: 
  distill::distill_article:
    toc: true
    toc_depth: 3
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo=FALSE, 
  message=FALSE, 
  warning=FALSE,
  dev = "ragg_png",
  cache = FALSE
  )

source("data_cleaning/00_library.R")
source("data_cleaning/01_functions.R")
source("data_cleaning/01_functions_visuals.R")
source("data_cleaning/rdas.R")
```


<br>

# Overview

```{r}
# Coos only has charge descriptions, codes (sometimes),and booking types
data1 <- SAVE_adm_all %>%
  filter(county == "Coos") %>%
  select(id,
         booking_id,
         charge_code,
         charge_desc,
         booking_type,
         booking_type_standard,
         sentence_status,
         release_type
         ) %>%
  distinct() %>%
  group_by(#charge_code,
           #charge_desc,
           booking_type,
           booking_type_standard,
           sentence_status,
           release_type) %>%
  summarise(total = n()) %>% 
  arrange(booking_type_standard)

# Custom function for booking recordings table
# Shows how each county records things differently
(table1 <- fnc_reactable_booking_recordings(data1))
```

<br>

### DUAL STATUS

```{r}
data1 <- SAVE_adm_all %>%
  filter(county == "Coos") %>%
  filter(sentence_status == "DUAL STATUS") %>% 
  select(id,
         booking_id,
         charge_code,
         charge_desc,
         booking_type,
         booking_type_standard,
         sentence_status,
         release_type
         ) %>%
  distinct() %>%
  group_by(#charge_code,
           charge_desc,
           #booking_type,
           booking_type_standard,
           sentence_status,
           release_type) %>%
  summarise(total = n()) %>% 
  arrange(sentence_status)

# Custom function for booking recordings table
# Shows how each county records things differently
(table1 <- fnc_reactable_charges_booking_recordings(data1))
```

<br>

### PRETRIAL

```{r}
data1 <- SAVE_adm_all %>%
  filter(county == "Coos") %>%
  filter(sentence_status == "PRETRIAL") %>% 
  select(id,
         booking_id,
         charge_code,
         charge_desc,
         booking_type,
         booking_type_standard,
         sentence_status,
         release_type
         ) %>%
  distinct() %>%
  group_by(#charge_code,
           charge_desc,
           #booking_type,
           booking_type_standard,
           sentence_status,
           release_type) %>%
  summarise(total = n()) %>% 
  arrange(sentence_status)

# Custom function for booking recordings table
# Shows how each county records things differently
(table1 <- fnc_reactable_charges_booking_recordings(data1))
```

<br>

### SENTENCED 

```{r}
data1 <- SAVE_adm_all %>%
  filter(county == "Coos") %>%
  filter(sentence_status == "SENTENCED") %>% 
  select(id,
         booking_id,
         charge_code,
         charge_desc,
         booking_type,
         booking_type_standard,
         sentence_status,
         release_type
         ) %>%
  distinct() %>%
  group_by(#charge_code,
           charge_desc,
           #booking_type,
           booking_type_standard,
           sentence_status,
           release_type) %>%
  summarise(total = n()) %>% 
  arrange(sentence_status)

# Custom function for booking recordings table
# Shows how each county records things differently
(table1 <- fnc_reactable_charges_booking_recordings(data1))
```

<br>
<br>
