---
output: 
  distill::distill_article:
    toc: true
    toc_depth: 3
    theme: theme.css
    self_contained: false
---

```{r include=FALSE}
source("data_cleaning/00_library.R")
source("data_cleaning/01_functions.R")
source("data_cleaning/01_functions_visuals.R")
source("data_cleaning/rdas.R")

county_name <- "Coos"
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo=FALSE, 
  message=FALSE, 
  warning=FALSE,
  #dev = "ragg_png",
  cache = FALSE
  )
```

# Incarceration Patterns

# Jail Bookings

Coming soon.

# Demographics

Coming soon.


# High Utilizers

## Top 1%

```{r, results='asis'}
temp <- county_hu_1_pct_prop %>% filter(county == county_name) %>% filter(high_utilizer_1_pct == "Yes") %>% select(freq) 
temp <- as.vector(temp)
cat("**High Utilizers, when defined as the people in the top 1% of entrances, accounted for ", round(temp$freq*100, 1), "% of all entrances between FY2019 and FY2021", ".**\n\n", sep = "")
```

```{r}
data1 <- county_hu_5_pct_prop %>% filter(county == county_name & high_utilizer_5_pct != "Total") %>% ungroup() %>% select(-county) %>% droplevels() 

table1 <- fnc_reactable_fy(data1)
table1
```
## Top 5%

```{r, results='asis'}
temp <- county_hu_10_pct_prop %>% filter(county == county_name) %>% filter(high_utilizer_10_pct == "Yes") %>% select(freq) 
temp <- as.vector(temp)
cat("**High Utilizers, when defined as the people in the top 10% of entrances, accounted for ", round(temp$freq*100, 1), "% of all entrances between FY2019 and FY2021", ".**\n\n", sep = "")
```

```{r}
data1 <- county_hu_10_pct_prop %>% filter(county == county_name & high_utilizer_10_pct != "Total") %>% ungroup() %>% select(-county) %>% droplevels() 

table1 <- fnc_reactable_fy(data1)
table1
```

---
title: "`r county_name` County"
---
