---
title: "Analysis Plan"
output: 
  distill::distill_article:
    toc: true
    toc_depth: 3
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  #dev = "ragg_png",
  cache = FALSE
  )
```

For main PPT, we will use GLOBAL (state level, for 9/10 jails) only; however, we also need at least basics at a LOCAL/per jail level, for vetting purposes with jail partners, and for the Mari/Josh idea of sharing a personal static dashboard to each county. For example:    

- 9 county jails, representing X% of NH’s population…were included 
- Number of jail bed available in these 9 county jails (anything public we can find on this?) 

# Incarceration Patterns 

CSG Justice Center staff will compare jail booking, population, and release trends over time; identify “high utilizers” across the state based on established criteria; and compare characteristics of people identified as high utilizers to those who are not. The following analysis questions will be addressed: 

## PART 1- INCARCERATION PATTERNS 

How many people were booked into New Hampshire jails annually?  

- Graphic: line plot or other, with state-level, annual admissions per year FY2019-2021   
- Accompanying statistic: average annual admissions per year (total admission/3)  
- “Local” version – both graphic and stats, but for single counties  

What were the most common jail admission and release types?  

- First, break up admissions into PC vs. criminal charge admissions.   
- Then, among criminal charges, show breakdown by: High level crime category (Property, Violent, Public order, etc.)   
- Among “public order” crimes, most common subgroups if possible (e.g. “public urination”, “disorderly conduct”, etc.)   
- For PC and for criminal charges, as separate categories, also show most common release types. (Bar plots or a table could work well here)  
- These calculations can be duplicated (meaning a single person might show up repeatedly, but we should just be aware of how often that’s happening)   

What was the average length of incarceration in jail? 

- Statistics: First, break up into PC vs. criminal charge admissions 
- Then, calculate the minimum, mean, median, and maximum jails stays  
- Graphic: show distribution (density plot?), with vertical lines for average (we can use median is the data are skewed, or mean if they’re somewhat normally distributed)   
- I wonder if we could potentially have a global distribution density plot, but then have 9 lines showing the average for each county as a visual to compare across counties. This is a low priority though.  

## PART 2 – HIGH UTILIZERS: DEFINITIONS & JAIL PATTERNS 

(Initial work needed in order to address these RQs – how to define high utilizers?)   
Key: We can try 2 definitions – #1 can be high utilizer of jails only; and #2 could be high utilizer of jail &/or BH issue &/or high utilizer of Medicaid   

Jail HU: Explore top 1%, 3%, and 5% (i.e. 99th percentile, etc.) of all bookings  

- For each of these definitions, what is the average # of bookings per 3 years, for high utilizers, vs. for non-HUs?  
- For each of these definitions, what % of all duplicated bookings are due to high utilizers? 
- Stated differently: 
- If we look at the top 1% of people – and let’s say they account for a total of 100 bookings, and there are 500 bookings total, we would be able to say that 1 out of 5 bookings is due to a HU 
- Would love a visualization that shows global distribution, with a vertical line showing the “HU” cutoff; vs. local distributions w/ their own “HU” cutoffs 
- After we explore and determine an appropriate definition, we can use it to address the RQs below.   

When DHHS data comes in, we can repeat this process to identify people who have BH needs. Then, we can also look at the top 1%, 3%, 5% of Medicaid users – but we’ll need to see the data first to determine how to measure this (e.g. total # of services vs. total # of Emergency rooms visits, there are a number of options)  

What percent of annual jail bookings were for people identified as high utilizers?   

- Look at all jail bookings, regardless of type or LOS   
- We could do a stacked bar plot with % HU vs. non-HU bookings, per year, and an average percentage for the 3 year period   

Did this percentage differ for protective custody bookings?   

- Repeat analysis from (a) but break data into PC/ criminal charge bookings   

What percent of the standing jail population did high utilizers account for? 

- Need to ask Team about methods here – for example, how do we choose the correct day to measure standing jail population? We would also want to vet this for sure with  
- Ideas: We could look at each quarter (so, 4 dates throughout the year), across all of NH – and estimate the # of people incarcerated on that day – this would be some work for sure because we’d need to look backwards and determine based on LOS who is still incarcerated at that time, etc.  
- Based on those 4 estimates, we could see how much they vary throughout the year and then use an average to help smooth out the variation; then calculate % HU 
- We may want to do this only for 2021, our final year of data, since we have 2 years prior records to pull from in terms of looking back at who was booked and remains incarcerated 

## PART 3 – CHARACTERISTICS OF HIGH UTILIZERS  

These have to be calculated using DHHS matched data. The only thing missing from DHHS data is a booking reason/type (PC, criminal charge) – so we need to use the jail admin data to develop good estimates of LOS that are indicative of a PC hold vs. criminal charge, and apply that to the DHHS data to estimate PC hold or not in that dataset. 

How did high utilizers compare to the rest of the jail population in terms of  

- Gender;   
- Race and ethnicity;   
- Annual number of jail incarcerations per person (PC and non-PC)  
- Length of stay in jail; (PC and non-PC)  
- Medicaid enrollment status or Medicaid eligibility;   
- Housing status (i.e., experiencing homelessness or housing instability); and  
- Indicators of substance use, mental illness, or trauma?   

For ALL of these we can look at simple differences (difference in means, difference in proportions), and then use t-tests/chi-square tests to determine if difference is statistically significant. 

We could also compare to NH Census demographics (HU vs. non-HU, jail pop vs. NH pop more broadly) - More info in analysis plan in SP.

### Treatment Patterns 

CSG Justice Center staff will summarize services received by high utilizers while incarcerated in jail (select counties), as well as services received in the community before incarceration and after release, to identify trends in activity and assess whether services received are related to identified risks and needs. The following analysis questions will be addressed: 
 
- What treatment, programming, or services did people with behavioral health needs receive while incarcerated in jail (select counties)?   
- First, contextualize results: indicate # of counties that had readily available BH data in an electronic format  
- Also describe some of the major limitations here that were common across jails (few have any standard BH need indicator, for example)  
- BRING TOGETHER QUAL AND QUANT DATA  
- Summarize most common types of BH programming/services available across the state  
- E.g. 1-on-1 counseling  
- Then summarize activities completed   
- E.g. # of program sessions attended/provided  
- # of counseling sessions provided  
- We can’t reliably compare HU/non-HUs here because there’s so little data  

What treatment, programming, or services did high utilizers receive in the community (via Medicaid) before and after incarceration in jail?  
 
- First, identify windows for study to ensure uniformity 
- We have 3 years total data 
- We could create 3- and 6-month windows prior and after incarceration, and see how many total windows that yields 
- Some people might only have pre-incarceration or post-incarceration window 
- New: We will have 5 years of Medicaid records for folks 
- Summarize (counts, percentages) major categories of community BH and other services 
- E.g. # of ER visits 
- Compare HU vs non-HU use of Medicaid services? 
