---
title: "Booking Types Analysis"
output: 
  distill::distill_article:
    toc: true
    toc_depth: 3
    theme: theme.css
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo=FALSE, 
  message=FALSE, 
  warning=FALSE,
  dev = "ragg_png",
  cache = FALSE
  )

source("data_cleaning/00_library.R")
source("data_cleaning/01_functions.R")
source("data_cleaning/01_functions_visuals.R")
source("data_cleaning/rdas.R")
```

# Booking Types

The following booking patterns were found using jail administrative data submitted directly to CSG.

## Table 1. Booking Types State-wide

```{r, out.width="75%", echo=FALSE, layout = "l-body"}
df_sentence_statuses <- bookings_entrances %>% select(sentence_status_standard, booking_id) %>% distinct() %>% 
  mutate(sentence_status_standard = ifelse(sentence_status_standard == "UNKNOWN", NA, sentence_status_standard)) 

df1 <- df_sentence_statuses %>% 
  group_by(sentence_status_standard) %>% 
  summarise(total = n()) %>% 
  filter(!is.na(sentence_status_standard)) %>% 
  mutate(sum = sum(total),
         yesno = "Yes") %>% 
  mutate(difference = sum-total)
temp <- df1 %>% 
    mutate(yesno = "No") %>% 
    select(-c(total, sum)) %>% 
    rename(total = difference)
df1 <- df1 %>% select(-c(sum, difference))
df1 <- rbind(df1, temp)

df1 <- group_by(df1, sentence_status_standard) %>% mutate(pct = total/sum(total)*100) %>%
  mutate(pct = round(pct, 0),
         sentence_status_standard = case_when(
           sentence_status_standard == "PRETRIAL" ~ "Pretrial",
           sentence_status_standard == "PROTECTIVE CUSTODY" ~ "Protective Custody",
           sentence_status_standard == "SENTENCED" ~ "Sentenced",
           sentence_status_standard == "OTHER" ~ "Other",
           sentence_status_standard == "NH STATE PRISONER" ~ "NH State Prisoner"))

df1 <- as.data.frame(df1)
df1 <- df1 %>% mutate(pct = paste0(pct, "%"))
df1$sentence_status_standard <- factor(df1$sentence_status_standard,levels = c("NH State Prisoner",
                                                                               "Other",
                                                                               "Sentenced",
                                                                               "Protective Custody",
                                                                               "Pretrial"))

# percent barchart of booking types
ggplot(df1, aes(x = sentence_status_standard, y = total, fill = yesno)) +
  geom_col(colour = NA, position = "fill") +
  scale_y_continuous(labels = scales::percent,
                     expand = expansion(mult = c(0, .1))) +
  scale_fill_manual(values=c("lightgray", jri_green)) +
  geom_text(aes(label = pct, fontface = 'bold'), position = position_fill(vjust = 0.5),
            size = 7.5, family = "Franklin Gothic Book",
            color = ifelse(df1$yesno == "No", "lightgray", "white")) +
  theme_no_axes +
  theme(legend.position = "none",
        legend.justification = c(0, 0),
        legend.title=element_blank(),
        axis.title.y = element_blank(),
        axis.title.x = element_blank()) +
  coord_flip() 
```


```{r}
df_sentence_statuses <- data.frame(summarytools::freq(df_sentence_statuses$sentence_status_standard, order = "freq", cum.percent = FALSE))
df_sentence_statuses <- df_sentence_statuses %>% tibble::rownames_to_column("sentence_status_standard") %>%
  dplyr::select(`Booking Type` = sentence_status_standard,
                `Unique Bookings (N)` = Freq,
                `Proportion of Bookings (%)` = X..Valid) 
df_sentence_statuses <- df_sentence_statuses %>% 
  mutate(`Proportion of Bookings (%)` = percent(`Proportion of Bookings (%)`/100))

kable(df_sentence_statuses, 
      format.args = list(big.mark = ","), 
      align=rep('l')) %>%
  kable_styling(bootstrap_options = c("striped", 
                                       "hover", 
                                       "condensed", 
                                       "responsive"), 
                 row_label_position = "l") %>% 
  row_spec(7, bold = TRUE)
```

## Table 2. Booking Types by County (N)

```{r}
# Df of total number of entrances by county
df_entrances_county <- bookings_entrances %>%
  dplyr::ungroup() %>%
  dplyr::select(booking_id, county) %>%
  dplyr::distinct() %>%
  dplyr::group_by(county) %>%
  dplyr::summarise(total = n())

# Number of sentence types by county for all three years
df_sentence_statuses_county <- bookings_entrances %>%
  dplyr::ungroup() %>%
  dplyr::select(booking_id, county, sentence_status_standard) %>%
  dplyr::distinct() %>%
  dplyr::group_by(county, sentence_status_standard) %>%
  dplyr::summarise(total = n())

# Reshape table for viewing
df_sentence_statuses_county <- df_sentence_statuses_county %>% spread(sentence_status_standard, total) %>% clean_names() %>% 
  select(County                   = county,
         `Pretrial (N)`           = pretrial,
         `Protective Custody (N)` = protective_custody,
         `Sentenced (N)`          = sentenced,
         `Other (N)`              = other,
         `NH State Prisoner (N)`  = nh_state_prisoner,
         `Unknown (N)`            = unknown) %>% 
  left_join(df_entrances_county, by = c("County" = "county")) %>% 
  rename(`Total Entrances (N)` = total)

df_sentence_statuses_county_pct <- df_sentence_statuses_county %>% 
  mutate(`Pretrial %`             = percent(`Pretrial (N)`/`Total Entrances (N)`),
         `Protective Custody (%)` = percent(`Protective Custody (N)`/`Total Entrances (N)`),
         `Sentenced (%)`          = percent(`Sentenced (N)`/`Total Entrances (N)`),
         `Other (%)`              = percent(`Other (N)`/`Total Entrances (N)`),
         `NH State Prisoner (%)`  = percent(`NH State Prisoner (N)`/`Total Entrances (N)`),
         `Unknown (%)`            = percent(`Unknown (N)`/`Total Entrances (N)`)
         ) %>% 
  select(-c(
         `Pretrial (N)`,
         `Protective Custody (N)`,
         `Sentenced (N)`,
         `Other (N)`,
         `NH State Prisoner (N)`,
         `Unknown (N)`,
         `Total Entrances (N)`
  ))
  
kable(df_sentence_statuses_county, 
      format.args = list(big.mark = ","), 
      align=rep('l')) %>%
  kable_styling(bootstrap_options = c("striped", 
                                       "hover", 
                                       "condensed", 
                                       "responsive"), 
                 row_label_position = "l") %>% 
   column_spec(1, bold = T, width = "12em") %>% 
   column_spec(2, width = "8em") %>% 
   column_spec(3, width = "8em") %>% 
   column_spec(4, width = "8em") %>% 
   column_spec(5, width = "8em") %>% 
   column_spec(6, width = "8em") %>% 
   column_spec(7, width = "8em") %>% 
   column_spec(8, width = "8em")
```

## Table 3. Booking Types by County (%)

```{r}
kable(df_sentence_statuses_county_pct, 
      format.args = list(big.mark = ","), 
      align=rep('l')) %>%
  kable_styling(bootstrap_options = c("striped", 
                                       "hover", 
                                       "condensed", 
                                       "responsive"), 
                 row_label_position = "l") %>% 
   column_spec(1, bold = T, width = "12em") %>% 
   column_spec(2, width = "8em") %>% 
   column_spec(3, width = "8em") %>% 
   column_spec(4, width = "8em") %>% 
   column_spec(5, width = "8em") %>% 
   column_spec(6, width = "8em") %>% 
   column_spec(7, width = "8em") 
```

# Booking Types and Associated Charges

```{r}
df1 <- adm_all %>% group_by(crime_type_lookup, sentence_status_standard) %>% summarise(total = n()) %>% 
  mutate(sentence_status_standard = case_when(
           sentence_status_standard == "PRETRIAL" ~ "Pretrial",
           sentence_status_standard == "PROTECTIVE CUSTODY" ~ "Protective Custody",
           sentence_status_standard == "SENTENCED" ~ "Sentenced",
           sentence_status_standard == "OTHER" ~ "Other",
           sentence_status_standard == "NH STATE PRISONER" ~ "NH State Prisoner",
           is.na(sentence_status_standard) == "Unknown")) 
df1$sentence_status_standard <- factor(df1$sentence_status_standard,levels = c("Pretrial",
                                                                               "Protective Custody",
                                                                               "Sentenced",
                                                                               "Other",
                                                                               "NH State Prisoner",
                                                                               "Unknown"))

df1 <- spread(df1, key = sentence_status_standard, value = total)
df1 <- df1 %>% rename(`Crime Type` = crime_type_lookup)
kable(df1, 
      format.args = list(big.mark = ","), 
      align=rep('l')) %>%
  kable_styling(bootstrap_options = c("striped", 
                                       "hover", 
                                       "condensed", 
                                       "responsive"), 
                 row_label_position = "l") %>% 
   column_spec(1, bold = T, width = "20em") %>% 
   column_spec(2, width = "8em") %>% 
   column_spec(3, width = "8em") %>% 
   column_spec(4, width = "8em") %>% 
   column_spec(5, width = "8em") %>% 
   column_spec(6, width = "8em") %>% 
   column_spec(7, width = "8em") 
```

