---
title: "Cheshire County Trends"
output: 
  distill::distill_article:
    toc: true
    toc_depth: 3
    self_contained: false
---

```{r include=FALSE}
# call libraries
library(easypackages)
libraries("tidyverse","foreign","lubridate","reshape2", "ggplot2","RColorBrewer","knitr","forcats","openxlsx","statar","svDialogs","xlsx", "magrittr","stringr", "data.table","janitor","kableExtra","leaflet", "readr", "rmarkdown","rowr", "gganimate", "gifski","tidycensus","sf","htmltools","acs","tigris","mapview","rgeos", "ggrepel", "censusxy","gdata","lavaan","mclust","tmap","scales","raster","rgeos","gmapsdistance","viridis","cowplot","lintr","leaflet.extras","censusapi","data.table","gridGraphics","readxl","haven","ggridges","extrafont","extrafontdb","datamodelr","Lahman","DiagrammeR","fs","readxl","rsvg","V8","ragg","ggtext","csgjcr","distill","ezknitr")

source("data_cleaning/00_library.R")
source("data_cleaning/01_functions.R")
source("data_cleaning/06_dataframes.R")
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo=FALSE, 
  message=FALSE, 
  warning=FALSE,
  dev = "ragg_png",
  cache = FALSE
  )
```

```{r include=FALSE}
### set theme
theme_set(theme_minimal())
```

# Jail admissions

### Demographics

#### Race/Ethnicity

```{r}
# How many people are booked into New Hampshire jails annually?
# What are the most common jail admission and release types
# What is the average length of incarceration in jail?   
# How are protective custody holds factored into the jail population?

# booking numbers by race ethnicity and FY
fnc_freq_table(cheshire_race, "Race/Ethnicity") 
```

#### Sex

```{r}
fnc_freq_table(cheshire_sex, "Sex")
```

### Booking Type

```{r}
fnc_booking_heatmap(cheshire_heatmap)
```

```{r}
# booking numbers by booking type and FY
fnc_freq_table(cheshire_booking, "Booking Type")
```

### Sentence Status

```{r}
# booking numbers by sentence status and FY
fnc_freq_table(cheshire_sentence, "Sentence Status")
```

# High Utilizers

### Sentence Status

Sentence status types of high utilizers (numbers represent individual bookings, not the number of individuals).  

```{r}
#What percent of annual jail bookings are for people identified as high utilizers? What is the threshold? 
#Is this percentage different for protective custody bookings?   
#What percent of the daily jail population do high utilizers account for? 
#How does the high utilizer jail population compare to others in jail in terms of gender, race, and ethnicity?   
#What other indicators exist among the high utilizer population in jail including their Medicaid enrollment status or Medicaid eligibility, their housing status, and indicators of substance use and/or mental illness?  

# booking numbers by race ethnicity and FY
fnc_freq_table(cheshire_hu_sentence, "Sentence Status")
```
