---
title: "Carroll County Trends"
output: 
  distill::distill_article:
    toc: true
    toc_depth: 3
    self_contained: false
---

```{r include=FALSE}
source("data_cleaning/00_library.R")
source("data_cleaning/01_functions.R")
source("data_cleaning/13_dataframes.R")
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo=FALSE, 
  message=FALSE, 
  warning=FALSE,
  #dev = "ragg_png",
  cache = FALSE
  )
```

# Jail admissions

### Demographics

```{r}
fnc_freq_table(carroll_race, "Race/Ethnicity") 
```

```{r}
fnc_freq_table(carroll_sex, "Sex")
```

### Booking Type

```{r}
fnc_booking_heatmap(carroll_heatmap)
```

```{r}
fnc_freq_table(carroll_bookings, "Booking Type")
```

```{r}
carroll_pch_time_highchart
```

### Sentence Status

```{r}
fnc_freq_table(carroll_sentence, "Sentence Status")
```

# High Utilizers

High utilizers are defined as individuals who were booked into jail more than 3 times in a fiscal year.  

```{r}
fnc_freq_table(carroll_hu, "High Utilizer")
```

### Demographics

```{r}
fnc_freq_table(carroll_hu_race, "Race/Ethnicity") 
```

```{r}
fnc_freq_table(carroll_hu_sex, "Sex")
```

### Booking Type

```{r}
fnc_freq_table(carroll_hu_booking, "Booking Type")
```

### Sentence Status

```{r}
fnc_freq_table(carroll_hu_sentence, "Sentence Status")
```
