---
title: "Data Dictionary"
output: 
  distill::distill_article:
    toc: true
    toc_depth: 3
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo=FALSE, 
  message=FALSE, 
  warning=FALSE,
  #dev = "ragg_png",
  cache = FALSE
  )
```

```{r include=FALSE}
# load data
load(paste0(sp_data_path, "/Data/r_data/raw_adm_data_availability_table.Rda", sep = ""))
load(paste0(sp_data_path, "/Data/r_data/belknap_adm.Rda",      sep = ""))
load(paste0(sp_data_path, "/Data/r_data/carroll_adm.Rda",      sep = ""))
load(paste0(sp_data_path, "/Data/r_data/cheshire_adm.Rda",     sep = ""))
load(paste0(sp_data_path, "/Data/r_data/coos_adm.Rda",         sep = ""))
load(paste0(sp_data_path, "/Data/r_data/hillsborough_adm.Rda", sep = ""))
load(paste0(sp_data_path, "/Data/r_data/merrimack_adm.Rda",    sep = ""))
load(paste0(sp_data_path, "/Data/r_data/rockingham_adm.Rda",   sep = ""))
load(paste0(sp_data_path, "/Data/r_data/strafford_adm.Rda",    sep = ""))
load(paste0(sp_data_path, "/Data/r_data/sullivan_adm.Rda",     sep = ""))
```

# Jail Data Availability 

NH is not on a unified system so data availability varied by county.  

```{r}
raw_adm_data_availability_table
```

# Data Dictionaries

## Belknap  

```{r}
not_all_na <- function(x) any(!is.na(x))
df <- belknap_adm1 %>% dplyr::select_if(not_all_na)
view_df(df)
```

## Carroll  

```{r}
df <- carroll_adm1 %>% dplyr::select_if(not_all_na)
view_df(df)
```

## Cheshire  

```{r}
df <- cheshire_adm1 %>% dplyr::select_if(not_all_na)
view_df(df)
```

## Coos

```{r}
df <- coos_adm1 %>% dplyr::select_if(not_all_na)
view_df(df)
```

## Hillsborough

```{r warning=FALSE}
df <-hillsborough_adm1 %>% dplyr::select_if(not_all_na)
view_df(df)
```

## Merrimack  

```{r}
df <- merrimack_adm1 %>% dplyr::select_if(not_all_na)
view_df(df)
```

## Rockingham

```{r}
df <- rockingham_adm1 %>% dplyr::select_if(not_all_na)
view_df(df)
```

## Strafford

```{r}
df <- strafford_adm1 %>% dplyr::select_if(not_all_na)
view_df(df)
```

## Sullivan

```{r}
df <- sullivan_adm1 %>% dplyr::select_if(not_all_na)
view_df(df)
```
