---
title: "High Utilizers Trends (DHHS Data)"
output: 
  distill::distill_article:
    toc: true
    toc_depth: 3
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo=FALSE, 
  message=FALSE, 
  warning=FALSE,
  #dev = "ragg_png",
  cache = FALSE
  )

source("data_cleaning/00_library.R")
source("data_cleaning/01_functions.R")
source("data_cleaning/01_functions_visuals.R")
medicaid_jail_all <- read_rds("D:/Analytic/medicaid_jail_all.rds") 
```

# How we define High Utilizers

We defined high utilizers (HU) as the top 1%, 5%, or 10% of people booked into jails from FY2019 to FY2021.

```{r}
# DHHS data
# create temporary id for function and create fy variable
entrances_dhhs <- medicaid_jail_all %>% 
  mutate(id = unique_person_id,
         fy = case_when(booking_date > "2018-06-30" & booking_date < "2019-07-01" ~ 2019,
                        booking_date > "2019-06-30" & booking_date < "2020-07-01" ~ 2020,
                        booking_date > "2020-06-30" & booking_date < "2021-07-01" ~ 2021))

# Number of people entered by county for all three years
amt_people_entered_county <- entrances_dhhs %>%
  dplyr::ungroup() %>%
  dplyr::select(id, county) %>%
  dplyr::distinct() %>%
  dplyr::group_by(county) %>%
  dplyr::summarise(total = n())

# Df of total number of people entered by FY by county
df_people_entered_county <- entrances_dhhs %>%
  dplyr::ungroup() %>%
  dplyr::select(id, fy, county) %>%
  dplyr::distinct() %>%
  dplyr::group_by(fy, county) %>%
  dplyr::summarise(total = n()) %>%
  spread(fy, total) %>%
  mutate(`2019` = as.numeric(`2019`),
         `2020` = as.numeric(`2020`),
         `2021` = as.numeric(`2021`)) %>%
  left_join(amt_people_entered_county, by = "county") %>%
  adorn_totals("row") %>%
  mutate(change_19_21 = (`2021`-`2019`)/`2019`) %>%
  mutate(county = case_when(county == "Coos" ~ "Coos (bookings only)",
                            county == "Total" ~ "State",
                            TRUE ~ county))

# Number of entrances by county for all three years
amt_entrances_county <- entrances_dhhs %>%
  dplyr::ungroup() %>%
  dplyr::select(booking_id, county) %>%
  dplyr::distinct() %>%
  dplyr::group_by(county) %>%
  dplyr::summarise(total = n())

# Df of total number of entrances by FY
df_entrances_county <- entrances_dhhs %>%
  dplyr::ungroup() %>%
  dplyr::select(booking_id, fy, county) %>%
  dplyr::distinct() %>%
  dplyr::group_by(fy, county) %>%
  dplyr::summarise(total = n()) %>%
  spread(fy, total) %>%
  mutate(`2019` = as.numeric(`2019`),
         `2020` = as.numeric(`2020`),
         `2021` = as.numeric(`2021`)) %>%
  left_join(amt_entrances_county, by = "county")

df_entrances_county <- df_entrances_county %>%
  adorn_totals("row") %>%
  mutate(change_19_21 = (`2021`-`2019`)/`2019`) %>%
  mutate(county = case_when(county == "Coos" ~ "Coos (bookings only)",
                            county == "Total" ~ "State",
                            TRUE ~ county))

# Average number of entrances/fy by county
df_avg_entrances_county <- entrances_dhhs %>%
  ungroup() %>%
  select(county, id, num_entrances) %>%
  distinct() %>%
  group_by(county) %>%
  dplyr::summarize(avg_entrances = mean(num_entrances, na.rm=TRUE)) %>%
  mutate(county = case_when(county == "Coos" ~ "Coos (bookings only)", TRUE ~ county))

# Average number of entrances/fy by state
df_avg_entrances_total <- entrances_dhhs %>%
  ungroup() %>%
  select(id, num_entrances) %>%
  distinct() %>%
  group_by() %>%
  dplyr::summarize(avg_entrances = mean(num_entrances, na.rm=TRUE)) %>%
  mutate(county = "State")

# Add county and state info together
df_avg_entrances_county <- rbind(df_avg_entrances_county, df_avg_entrances_total)

# Rename variables and add data together
df_entrances_county <- df_entrances_county %>% rename_with(~paste0("entrances_", .), -c("county")) 
df_entrances_people_county <- df_people_entered_county %>% rename_with(~paste0("people_entered_", .), -c("county"))
df_entrances_table <- merge(df_entrances_county, df_entrances_people_county, by = "county", all.x = TRUE, all.y = TRUE)
df_entrances_table <- merge(df_entrances_table, df_avg_entrances_county, by = "county", all.x = TRUE, all.y = TRUE)

# Summary info for each type of HU
# Ignore warnings
df_hu_4_times_summary <- fnc_hus_descriptive_summary(entrances_dhhs, "high_utilizer_4_times", "Yes", "Coos (bookings only)")
df_hu_1_pct_summary   <- fnc_hus_descriptive_summary(entrances_dhhs, "high_utilizer_1_pct",   "Yes", "Coos (bookings only)")
df_hu_5_pct_summary   <- fnc_hus_descriptive_summary(entrances_dhhs, "high_utilizer_5_pct",   "Yes", "Coos (bookings only)")
df_hu_10_pct_summary  <- fnc_hus_descriptive_summary(entrances_dhhs, "high_utilizer_10_pct",  "Yes", "Coos (bookings only)")

# reactable tables by HU (will combine for presentations)
table_hu_4_times_summary <- fnc_reactable_hus_descriptive_summary(df_hu_4_times_summary)
table_hu_1_pct_summary   <- fnc_reactable_hus_descriptive_summary(df_hu_1_pct_summary)
table_hu_5_pct_summary   <- fnc_reactable_hus_descriptive_summary(df_hu_5_pct_summary)
table_hu_10_pct_summary  <- fnc_reactable_hus_descriptive_summary(df_hu_10_pct_summary)

# Subset data for total entrances (HU and non-HU), total people, and average number of entrances a year
# Created in incarceration_patterns_entrances.R
df_entrances1 <- df_entrances_table %>% select(county, entrances_total, people_entered_total, avg_entrances)

# Add labels to metrics to identify 1, 5, and 10%
data_1_pct <- df_hu_1_pct_summary  %>% rename_with(~paste0(., "_1_pct"),  -c("county"))
data_5_pct <- df_hu_5_pct_summary  %>% rename_with(~paste0(., "_5_pct"),  -c("county"))
data_10_pct <- df_hu_10_pct_summary %>% rename_with(~paste0(., "_10_pct"), -c("county"))

# Combine county entrances and county HU entrances info
df_1_5_10 <- df_entrances1 %>%
  left_join(data_1_pct, by = "county") %>%
  left_join(data_5_pct, by = "county") %>%
  left_join(data_10_pct, by = "county") %>%
  mutate(freq_1_pct = total_hu_entrances_1_pct/entrances_total,
         freq_5_pct = total_hu_entrances_5_pct/entrances_total,
         freq_10_pct = total_hu_entrances_10_pct/entrances_total) %>%
  mutate(range_1_pct = paste(min_1_pct, max_1_pct, sep = "-"),
         range_5_pct = paste(min_5_pct, max_5_pct, sep = "-"),
         range_10_pct = paste(min_10_pct, max_10_pct, sep = "-")) %>%
  arrange(county %in% "State")
```

```{r}
# Reactable table for presentation showing the number of HU's, min, med, mean, max, etc.
reactable(df_1_5_10,
          pagination = FALSE,
          style = list(fontFamily = "Franklin Gothic Book", fontSize = "1.0rem"),
          rowStyle = function(index) {
            if (index %in% c(10)) {
              list(`border-top` = "thin solid",
                   fontWeight = "bold")
            }
          },
          columnGroups = list(
            colGroup(name = "Top 1% HU's",  columns = c("total_hu_entrances_1_pct",  "total_hu_people_1_pct",  
                                                        "freq_1_pct",  "min_1_pct",  "median_1_pct", "mean_1_pct", 
                                                        "max_1_pct", "range_1_pct")),
            colGroup(name = "Top 5% HU's",  columns = c("total_hu_entrances_5_pct",  "total_hu_people_5_pct",  
                                                        "freq_5_pct",  "min_5_pct",  "median_5_pct", "mean_5_pct", 
                                                        "max_5_pct", "range_5_pct")),
            colGroup(name = "Top 10% HU's",  columns = c("total_hu_entrances_10_pct", "total_hu_people_10_pct", 
                                                         "freq_10_pct", "min_10_pct", "median_10_pct", "mean_10_pct", 
                                                         "max_10_pct", "range_10_pct"))
          ),
          theme = reactableTheme(cellStyle = list(display = "flex", flexDirection = "column", justifyContent = "center"),
                                 headerStyle = list(display = "flex", flexDirection = "column", justifyContent = "center")),
          defaultColDef = reactable::colDef(
            format = colFormat(separators = TRUE), align = "center"),
          compact = TRUE,
          fullWidth = FALSE,
          columns = list(
            county                = colDef(show = T, minWidth = 190, name = "County", align = "left",
                                           style = list(fontWeight = "bold", position = "sticky", borderRight = "1px solid #d3d3d3")),
            entrances_total       = colDef(show = F, minWidth = 100, name = "Total Entrances"),
            people_entered_total  = colDef(show = F, minWidth = 100,  name = "Total People"),
            avg_entrances         = colDef(show = F, minWidth = 130, name = "Avg Entrances Per Person",
                                           format = colFormat(percent = FALSE, digits = 1),
                                           style = list(fontWeight = "bold", position = "sticky", borderRight = "1px solid #d3d3d3")),

            total_hu_entrances_1_pct = colDef(show = F, minWidth = 100, name = "HU's (Entrances)"),
            total_hu_people_1_pct    = colDef(show = F, minWidth = 100, name = "HU's (People)"),
            freq_1_pct               = colDef(show = F, minWidth = 100, name = "Proportion of HU Entrances",
                                              style = list(fontWeight = "bold", position = "sticky", borderRight = "1px solid #d3d3d3"),
                                              format = colFormat(percent = TRUE, digits = 1)),
            min_1_pct                = colDef(show = F, minWidth = 100, name = "Minimum Number of Entrances Per Person"),
            median_1_pct             = colDef(show = T, minWidth = 100, name = "Median Number of Entrances Per Person"),
            mean_1_pct               = colDef(show = T, minWidth = 130, name = "Avg Number of Entrances Per Person", format = colFormat(percent = FALSE, digits = 1)),
            range_1_pct              = colDef(show = T, minWidth = 100, name = "Min - Max Number of Entrances Per Person",
                                              style = list(position = "sticky", borderRight = "1px solid #d3d3d3")),

            max_1_pct                = colDef(show = F, minWidth = 130, name = "Maximum Number of Entrances Per Person",
                                              style = list(position = "sticky", borderRight = "1px solid #d3d3d3")),

            total_hu_entrances_5_pct = colDef(show = F, minWidth = 100, name = "HU's (Entrances)"),
            total_hu_people_5_pct    = colDef(show = F, minWidth = 100, name = "HU's (People)"),
            freq_5_pct               = colDef(show = F, minWidth = 100, name = "Proportion of HU Entrances",
                                              style = list(fontWeight = "bold", position = "sticky", borderRight = "1px solid #d3d3d3"),
                                              format = colFormat(percent = TRUE, digits = 1)),
            min_5_pct                = colDef(show = F, minWidth = 100, name = "Minimum Number of Entrances Per Person"),
            median_5_pct             = colDef(show = T, minWidth = 100, name = "Median Number of Entrances Per Person"),
            mean_5_pct               = colDef(show = T, minWidth = 130, name = "Avg Number of Entrances Per Person", format = colFormat(percent = FALSE, digits = 1)),
            range_5_pct              = colDef(show = T, minWidth = 100, name = "Min - Max Number of Entrances Per Person",
                                              style = list(position = "sticky", borderRight = "1px solid #d3d3d3")),

            max_5_pct                = colDef(show = F, minWidth = 130, name = "Maximum Number of Entrances Per Person",
                                              style = list(position = "sticky", borderRight = "1px solid #d3d3d3")),

            total_hu_entrances_10_pct = colDef(show = F, minWidth = 100, name = "HU's (Entrances)"),
            total_hu_people_10_pct    = colDef(show = F, minWidth = 100, name = "HU's (People)"),
            freq_10_pct               = colDef(show = F, minWidth = 100, name = "Proportion of HU Entrances",
                                               style = list(fontWeight = "bold", position = "sticky", borderRight = "1px solid #d3d3d3"),
                                               format = colFormat(percent = TRUE, digits = 1)),
            min_10_pct                = colDef(show = F, minWidth = 100, name = "Minimum Number of Entrances Per Person"),
            median_10_pct             = colDef(show = T, minWidth = 100, name = "Median Number of Entrances Per Person"),
            mean_10_pct               = colDef(show = T, minWidth = 130, name = "Avg Number of Entrances Per Person", format = colFormat(percent = FALSE, digits = 1)),
            range_10_pct              = colDef(show = T, minWidth = 100, name = "Min - Max Number of Entrances Per Person"),

            max_10_pct                = colDef(show = F, minWidth = 130, name = "Maximum Number of Entrances Per Person",
                                              style = list(position = "sticky", borderRight = "1px solid #d3d3d3"))

))
```

```{r}
reactable(df_1_5_10,
          pagination = FALSE,
          style = list(fontFamily = "Franklin Gothic Book", fontSize = "1.0rem"),
          rowStyle = function(index) {
            if (index %in% c(10)) {
              list(`border-top` = "thin solid",
                   fontWeight = "bold")
            }
          },
          columnGroups = list(
            colGroup(name = "Top 1% HU's",  columns = c("total_hu_entrances_1_pct",  "total_hu_people_1_pct",  
                                                        "freq_1_pct",  "min_1_pct",  "median_1_pct", 
                                                        "mean_1_pct", "max_1_pct", "range_1_pct")),
            colGroup(name = "Top 5% HU's",  columns = c("total_hu_entrances_5_pct",  "total_hu_people_5_pct",  
                                                        "freq_5_pct",  "min_5_pct",  "median_5_pct", 
                                                        "mean_5_pct", "max_5_pct", "range_5_pct")),
            colGroup(name = "Top 10% HU's",  columns = c("total_hu_entrances_10_pct", "total_hu_people_10_pct", 
                                                         "freq_10_pct", "min_10_pct", "median_10_pct", 
                                                         "mean_10_pct", "max_10_pct", "range_10_pct"))
          ),
          theme = reactableTheme(cellStyle = list(display = "flex", flexDirection = "column", justifyContent = "center"),
                                 headerStyle = list(display = "flex", flexDirection = "column", justifyContent = "center")),
          defaultColDef = reactable::colDef(
            format = colFormat(separators = TRUE), align = "center"),
          compact = TRUE,
          fullWidth = FALSE,
          columns = list(
            county                = colDef(show = T, minWidth = 190, name = "County", align = "left",
                                           style = list(fontWeight = "bold", position = "sticky", borderRight = "1px solid #d3d3d3")),
            entrances_total       = colDef(show = F, minWidth = 100, name = "Total Entrances"),
            people_entered_total  = colDef(show = F, minWidth = 100,  name = "Total People"),
            avg_entrances         = colDef(show = F, minWidth = 130, name = "Avg Entrances Per Person",
                                           format = colFormat(percent = FALSE, digits = 1),
                                           style = list(fontWeight = "bold", position = "sticky", borderRight = "1px solid #d3d3d3")),

            total_hu_entrances_1_pct = colDef(show = T, minWidth = 100, name = "HU's (Entrances)"),
            total_hu_people_1_pct    = colDef(show = T, minWidth = 100, name = "HU's (People)"),
            freq_1_pct               = colDef(show = T, minWidth = 100, name = "Proportion of HU Entrances",
                                              style = list(fontWeight = "bold", position = "sticky", borderRight = "1px solid #d3d3d3"),
                                              format = colFormat(percent = TRUE, digits = 1)),
            min_1_pct                = colDef(show = F, minWidth = 100, name = "Minimum Number of Entrances Per Person"),
            median_1_pct             = colDef(show = F, minWidth = 100, name = "Median Number of Entrances Per Person"),
            mean_1_pct               = colDef(show = F, minWidth = 130, name = "Avg Number of Entrances Per Person", format = colFormat(percent = FALSE, digits = 1)),
            range_1_pct              = colDef(show = F, minWidth = 100, name = "Min - Max Number of Entrances Per Person",
                                              style = list(position = "sticky", borderRight = "1px solid #d3d3d3")),

            max_1_pct                = colDef(show = F, minWidth = 130, name = "Maximum Number of Entrances Per Person",
                                              style = list(position = "sticky", borderRight = "1px solid #d3d3d3")),

            total_hu_entrances_5_pct = colDef(show = T, minWidth = 100, name = "HU's (Entrances)"),
            total_hu_people_5_pct    = colDef(show = T, minWidth = 100, name = "HU's (People)"),
            freq_5_pct               = colDef(show = T, minWidth = 100, name = "Proportion of HU Entrances",
                                              style = list(fontWeight = "bold", position = "sticky", borderRight = "1px solid #d3d3d3"),
                                              format = colFormat(percent = TRUE, digits = 1)),
            min_5_pct                = colDef(show = F, minWidth = 100, name = "Minimum Number of Entrances Per Person"),
            median_5_pct             = colDef(show = F, minWidth = 100, name = "Median Number of Entrances Per Person"),
            mean_5_pct               = colDef(show = F, minWidth = 130, name = "Avg Number of Entrances Per Person", format = colFormat(percent = FALSE, digits = 1)),
            range_5_pct              = colDef(show = F, minWidth = 100, name = "Min - Max Number of Entrances Per Person",
                                              style = list(position = "sticky", borderRight = "1px solid #d3d3d3")),

            max_5_pct                = colDef(show = F, minWidth = 130, name = "Maximum Number of Entrances Per Person",
                                              style = list(position = "sticky", borderRight = "1px solid #d3d3d3")),

            total_hu_entrances_10_pct = colDef(show = T, minWidth = 100, name = "HU's (Entrances)"),
            total_hu_people_10_pct    = colDef(show = T, minWidth = 100, name = "HU's (People)"),
            freq_10_pct               = colDef(show = T, minWidth = 100, name = "Proportion of HU Entrances",
                                               style = list(fontWeight = "bold"),
                                               format = colFormat(percent = TRUE, digits = 1)),
            min_10_pct                = colDef(show = F, minWidth = 100, name = "Minimum Number of Entrances Per Person"),
            median_10_pct             = colDef(show = F, minWidth = 100, name = "Median Number of Entrances Per Person"),
            mean_10_pct               = colDef(show = F, minWidth = 130, name = "Avg Number of Entrances Per Person", format = colFormat(percent = FALSE, digits = 1)),
            range_10_pct              = colDef(show = F, minWidth = 100, name = "Min - Max Number of Entrances Per Person",
                                               style = list(position = "sticky", borderRight = "1px solid #d3d3d3")),

            max_10_pct                = colDef(show = F, minWidth = 130, name = "Maximum Number of Entrances Per Person",
                                               style = list(position = "sticky", borderRight = "1px solid #d3d3d3"))

          ))
```

<br>

# Top 1%

```{r}
table_hu_1_pct_summary
```

<br>

# Top 5%

```{r}
table_hu_5_pct_summary
```

<br>

# Top 10%

```{r}
table_hu_10_pct_summary
```

<br>
