---
title: "Incarceration Patterns"
output: 
  distill::distill_article:
    toc: true
    toc_depth: 3
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo=FALSE, 
  message=FALSE, 
  warning=FALSE,
  #dev = "ragg_png",
  cache = FALSE
  )

# load packages
source("data_cleaning/00_library.R")

# load data
load(paste0(sp_data_path, "/Data/r_data/nh_people_booked_amt.Rda",      sep = ""))
load(paste0(sp_data_path, "/Data/r_data/nh_counties.Rda",               sep = ""))

load(paste0(sp_data_path, "/Data/r_data/nh_people_booked.Rda",          sep = ""))
load(paste0(sp_data_path, "/Data/r_data/nh_people_booked_county.Rda",   sep = ""))
load(paste0(sp_data_path, "/Data/r_data/nh_people_booked_barchart.Rda", sep = ""))

load(paste0(sp_data_path, "/Data/r_data/nh_booked_change_19_20.Rda",    sep = ""))
load(paste0(sp_data_path, "/Data/r_data/nh_booked_change_20_21.Rda",    sep = ""))
load(paste0(sp_data_path, "/Data/r_data/nh_booked_change_19_21.Rda",    sep = ""))

load(paste0(sp_data_path, "/Data/r_data/nh_booking_by_fy.Rda",          sep = ""))
load(paste0(sp_data_path, "/Data/r_data/nh_pch_time_highchart.Rda",     sep = ""))
load(paste0(sp_data_path, "/Data/r_data/nh_pch_table.Rda",              sep = ""))
load(paste0(sp_data_path, "/Data/r_data/nh_pch_pct_amt.Rda",            sep = ""))
load(paste0(sp_data_path, "/Data/r_data/pch_counties.Rda",              sep = ""))
```

# Jail Admissions

### By County

```{r, results='asis'}
# print header for pc hold section
cat("**There were ", nh_people_booked_amt, " people were booked into NH jails from FY 2019 to FY 2021.**"," This finding was calculated using data from the following counties: ", nh_counties, ".\n\n", sep = "")
```
```{r}
nh_people_booked_barchart
```

```{r, results='asis'}
cat("**The number of people booked into jails has been decreasing. There was a ", nh_booked_change_19_20, "% decrease between FY2019 and FY2020, and ", nh_booked_change_20_21, "% decrease between FY2020 and FY2021. There was an overall decrease of ", nh_booked_change_19_21, "% between FY2019 and FY2021.\n\n", sep = "")
```
```{r}
nh_people_booked
```

### By County

Counties saw variations in the number of people booked into jails but they all saw a decrease in the past three years.

```{r}
nh_people_booked_county
```

<br>

# Protective Custody Holds

```{r, results='asis'}
# print header for pc hold section
cat("**Protective custody holds accounted for ", nh_pch_pct_amt, "% of bookings from 2019 to 2021.**"," This finding was calculated using data from the following counties: ", pch_counties, ".\n\n", sep = "")
```
**Although the number of people booked into jails has been decreasing, the proportion of PC holds has remained the same.**

```{r}
nh_pch_table 
```

```{r}
# protective custody holds over time
nh_pch_time_highchart %>%   
  hc_caption(text = paste("<em>Counties included: ", toString(pch_counties), "</em>")) 
```




