---
title: "Mari/Sara To Do"
output: 
  distill::distill_article:
    toc: true
    toc_depth: 3
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  #dev = "ragg_png",
  cache = FALSE
  )
```


## Questions  

- Should LOS include PC holds? Weekends?  
- Do we need to determine which charges are sex, violent, or drug offense?  
- Interested in part 1 violent crimes? 

# Visualization ideas

- [Bookings by type over time](https://app.powerbigov.us/view?r=eyJrIjoiMmRkMmNiOTEtNDBlNy00ZjIwLTk3OTQtYzQ5YTA0YzcxZGZmIiwidCI6ImU0YTM0MGU2LWI4OWUtNGU2OC04ZWFhLTE1NDRkMjcwMzk4MCJ9) 
- [Bookings with positive MH screen](https://www.tiftonison.com/dashboard-shows-mental-health-needs-at-johnson-county-jail/); [Another](https://viz.jocogov.org/t/Public/views/SteppingUp/Dashboard?%3Aembed=y&%3Aiid=1&%3AisGuestRedirectFromVizportal=y)
- [Response to covid](https://safetyandjusticechallenge.org/topics/data-analysis/)
- Did mental health/drug use increase after covid? 
- [Pathways from arrest -> booking -> release](https://www.prisonpolicy.org/reports/incomejails.html) 
- [Incarceration rates by race/ethnicity per 100,000 people in NH](https://www.prisonpolicy.org/graphs/2010rates/NH.html) 
- Map showing available MH services

## Belknap  

- Race categories: A, B, C, H, I, NH, O, P, U, W, X    
- Booking date range: 2018-07-01 - 2021-06-30  
- Housing: "Housed", "Unhoused"  
- No data: Ethnicity, release type, sentence status  

## Carroll  

- Race categories: A, B, I, U, W   
- Booking date range: 2018-07-01 - 2021-06-30  
- Housing: "Housed", "Unhoused"  
- No data: Ethnicity, release type is mostly missing

## Cheshire  

- Race categories: A, B, H, I, L, P, U, W   
- Booking date range: 2018-07-01 - 2021-06-29    
- Housing: All "Housed" - likely a data entry or excel issue  
- No data: Ethnicity, release type  

## Merrimack  

- Race categories: A, B, H, I, O, P, U, W, X     
- Date range: 2018-07-01 - 2021-06-30   
- Housing: "Housed", "Unhoused", "Unknown"  
- No data: Ethnicity, release type  

