---
title: "NH Medicaid Data Diagram"
author: Andrew Byrum
date: 'Janurary 2023'
output: html_document
---

### This syntax pulls in all data files provided by Uma of NH DHHS -- and maps their relationships with the datamodelr package (https://github.com/bergant/datamodelr)

Find DHHS-provided data dictionaries and code books in research folder at this path: `JR_NH\Data`

```{r include=FALSE}
### call libraries
library(easypackages)
libraries("tidyverse","foreign","lubridate","reshape2", "ggplot2","RColorBrewer","knitr","forcats","openxlsx","statar","svDialogs","xlsx", "magrittr","stringr", "data.table","janitor","kableExtra","leaflet", "readr", "rmarkdown","rowr", "gganimate", "gifski","tidycensus","sf","htmltools","acs","tigris","mapview","rgeos", "ggrepel", "censusxy","gdata","lavaan","mclust","tmap", "raster","rgeos","gmapsdistance","viridis","cowplot","lintr","leaflet.extras","censusapi","data.table","gridGraphics","readxl","haven","ggridges","extrafont","extrafontdb","datamodelr","Lahman","DiagrammeR","fs","readxl","rsvg","V8","csgjcr")
```

```{r include=FALSE}
### set path using csg_sp_path for data folder
sp_data_path <- csg_sp_path(file.path("JR_NH"))

### pull in medicaid data from external hard drive

# medicaid events
medicaid_encounters <- read_csv("D:/CSG-Encounters File 201407-202106.txt") %>% 
  clean_names()

# medicaid enrollment
medicaid_enrollment <- read_csv("D:/Medicaid Enrollment Data For County Matched Members.txt") %>% 
  clean_names()

# eligibility categories descriptions
medicaid_categories <- read_excel("D:/Categories of Eligibility Description.xlsx") %>% 
  clean_names()

# medicaid data dictionary (icd-10)
medicaid_dictionary <- read_excel(paste0(sp_data_path, "/Data/DHHS_data_dictionary.xlsx"), 
                                  sheet = "DX_to_CCSR_Mapping",
                                  skip = 1) %>% 
  clean_names()

### import medicaid_jail_all -- medicaid jail data that we'll compare to the numbers from the jail administrative files
### this file lives on the external hard drive (created and exported in `13_medicaid.R`)
medicaid_jail_all <- read_rds("D:/Analytic/medicaid_jail_all.rds") 

medicaid_jail_all_counties <- medicaid_jail_all %>% 
  clean_names() %>% 
  distinct(unique_person_id, 
           booking_id,
           .keep_all = TRUE) %>% 
  mutate(unique_person_booking_id = paste0(unique_person_id,
                                    booking_id)) ### creating unique booking id with both individual and booking IDs
```

```{r echo=FALSE,warning=FALSE,message=FALSE}
### create data map using datamodelr package; first, we have to name each table in the list we're creating, second we establish which columns are primary keys for each table via dm_set_key, and lastly we indicate how tables should be joined together -- which produces arrows between two tables via dm_add_references 
nh_medicaid_data_diagram <- list(medicaid_enrollment = medicaid_enrollment, 
                      medicaid_categories = medicaid_categories,
                      medicaid_encounters = medicaid_encounters, 
                      medicaid_dictionary = medicaid_dictionary,
                      medicaid_jail_all_counties = medicaid_jail_all_counties) %>% ### list dataframes to map
    dm_from_data_frames() %>%
    dm_set_key("medicaid_enrollment", c("unique_person_id","eligibility_category","eligiblity_begin_date",
                                        "eligiblity_end_date")) %>% ### set primary keys in each dataframe 
    dm_set_key("medicaid_categories", c("eligibility_code")) %>%
    dm_set_key("medicaid_encounters", c("unique_person_id","first_dos_dt","last_dos_dt","medicaid_reimb_amt")) %>%     
    dm_set_key("medicaid_dictionary", c("icd_10_cm_code","ccsr_category")) %>%
    dm_set_key("medicaid_jail_all_counties", c("unique_person_id","booking_id")) %>%
    dm_add_references(
        medicaid_categories$eligibility_code == medicaid_enrollment$eligibility_category, 
        medicaid_encounters$unique_person_id == medicaid_enrollment$unique_person_id,
        medicaid_encounters$first_dos_dt == medicaid_enrollment$eligiblity_begin_date,
        medicaid_encounters$first_dos_dt == medicaid_enrollment$eligiblity_end_date,
        medicaid_dictionary$icd_10_cm_code == medicaid_encounters$dx_prmry_cd_fnl, 
        medicaid_jail_all_counties$unique_person_id == medicaid_enrollment$unique_person_id, 
        medicaid_jail_all_counties$booking_date == medicaid_enrollment$eligiblity_begin_date, 
        medicaid_jail_all_counties$booking_date == medicaid_enrollment$eligiblity_end_date
        ) %>% 
    dm_create_graph(rankdir = "BT", columnArrows = FALSE, col_attr = c("column")) ### draw arrow to establish linkage relationship

### export data map as png file -- had to play around with height and width to render an image that kept legibility as user zooms in
dm_export_graph(nh_medicaid_data_diagram, 
                file_name = "C:/Users/abyrum/OneDrive - The Council of State Governments/Code/jr-nh/img/nh_medicaid_data_diagram.png",
                width = 1100, 
                height = 1400)
```
